### ISSUE TITLE
my ISP web-interface has self-signed certificate and I got errors

### ISSUE THREAD

**Issue by cypa** [ruslansvs2/ispmanager5cli#2]
honestly I've not found where in the code I should add --insecure option

```
[root@hyip ~]# ispcli --users
Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/ispcli", line 9, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/ispcli/menu.py", line 55, in main
    return load_data(names, query)
  File "/usr/lib/python3.6/site-packages/ispcli/main.py", line 27, in load_data
    return print_data(data.list(query), names)
  File "/usr/lib/python3.6/site-packages/ispcli/ispmanagerclass.py", line 65, in list
    return self.fetch_data(request_http(query))
  File "/usr/lib/python3.6/site-packages/ispcli/ispmanagerclass.py", line 37, in request_http
    return minidom.parse(urlopen(result))
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)>
```

**Comment by RuslanRWX** [comment]
Thank you for the feedback! 
I have added this feature and you can check it out. 
Pull the latest version (0.0.6) and try the following command:
   ispcli --users --insecure
